ENT.Type = "anim"
ENT.Base = "darkpower_powered_printerbase"
ENT.PrintName = "Tier 3 Powered Printer"
ENT.Spawnable = true
ENT.interval = 15
ENT.power_usage = 3
ENT.xoffset = -100
ENT.yoffset = -100
ENT.set_name = "Tier 3 Printer"
ENT.Category = "Darkpower"
