ENT.Type = "anim"
ENT.Base = "darkpower_powered_printerbase"
ENT.PrintName = "Tier 5 Powered Printer"
ENT.Spawnable = true
ENT.interval = 5
ENT.power_usage = 5
ENT.xoffset = -100
ENT.yoffset = -100
ENT.set_name = "Tier 5 Printer"
ENT.Category = "Darkpower"
