ENT.Type = "anim"
ENT.Base = "darkpower_generator_base"
ENT.PrintName = "Medium Generator"
ENT.Spawnable = true
ENT.maxpowered = 4
ENT.power_radius = 300
ENT.Category = "Darkpower"
ENT.xoffset = -100
ENT.yoffset = -400