ENT.Type = "anim"
ENT.Base = "darkpower_powered_printerbase"
ENT.PrintName = "Tier 2 Powered Printer"
ENT.Spawnable = true
ENT.interval = 20
ENT.power_usage = 2
ENT.xoffset = -100
ENT.yoffset = -100
ENT.set_name = "Tier 2 Printer"
ENT.Category = "Darkpower"
