ENT.Type = "anim"
ENT.Base = "darkpower_powered_base"
ENT.PrintName = "Armor Station"
ENT.Spawnable = true
ENT.power_usage = 2
ENT.xoffset = -100
ENT.yoffset = -125
ENT.set_name = "Armor Station"
ENT.Category = "Darkpower"