ENT.Type = "anim"
ENT.Base = "darkpower_powered_printerbase"
ENT.PrintName = "Tier 4 Powered Printer"
ENT.Spawnable = true
ENT.interval = 10
ENT.power_usage = 4
ENT.xoffset = -100
ENT.yoffset = -100
ENT.set_name = "Tier 4 Printer"
ENT.Category = "Darkpower"
