ENT.Type = "anim"
ENT.Base = "darkpower_powered_printerbase"
ENT.PrintName = "Tier 1 Powered Printer"
ENT.Spawnable = true
ENT.interval = 25
ENT.power_usage = 1
ENT.xoffset = -100
ENT.yoffset = -100
ENT.set_name = "Tier 1 Printer"
ENT.Category = "Darkpower"
